# Generated by Django 3.1.2 on 2021-09-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='number',
            new_name='numbers',
        ),
    ]
